### PR TITLE
Fix RCon kick

### PR DESCRIPTION
**Pull request by BoGuu**
rcon_kick is not really needed, however the fix for rcon_kick is also quite simple (this is for the red kick button). Might aswell just use command instead

### CODE REVIEW

**Comment by MightySCollins** [comment]
Has this been tested and is it working?

**Comment by BoGuu** [comment]
https://i.gyazo.com/87d155f0caa8784ff823630f26e2ac1d.jpg

This will just leave the little search icon to be fixed - as it's checking /players/BoGuu etc, instead of UID

**Comment by MightySCollins** [comment]
Nice but I am not sure there is a nice and easy way to fix that search... Its also broken when there is a space. I found a nice library for this, I will try and find it

**Comment by BoGuu** [comment]
Maybe just query with the name -> UID?
Or even, convert the GUID to PID?

**Comment by MightySCollins** [comment]
This might help: https://github.com/Nizarii/arma-rcon-class-php

**Pull request merged**
