### PR TITLE
donatorlvl -> donorlevel #41

### LINKED ISSUE #41: 4.4 Support for the players table
It doesn't seem to work on Altis Life 4.4r2. I have tested 4 different versions of cyberworks and none of them I was able to edit Bank, Cash, Coplevel, Adminlevel, Mediclevel.

The other functions seemed to work though.

Does this have something to do with that the database structure has been changed for the players table?

### PR DESCRIPTION
**Pull request by BoGuu**
This should fix #41, 4.4+ have changed to donorlevel, not donatorlvl.

### CODE REVIEW

**Comment by MightySCollins** [comment]
Only thing is will it break on earlier versions? If so it should check which DB field is used and use that.

**Comment by Kimax89** [comment]
@MightySCollins and thats why its a good practice to do a release every time you have a stable build for each version of AltisLife, So people who is running an older version can downgrade.

Or do different branches.

**Comment by BoGuu** [comment]
We have a system in the settings where you can switch between them. I'll look into adding it soon.

**Comment by Felix2** [comment]
Thank you, it's working now again :)

**Comment by MightySCollins** [comment]
@Kimax89 The problem with that is people will end up with versions which are out of date. Branches are even worse, you would end up with stale branches which are out of date and could end up with large merges.

It would also not be a good idea to do releases based on AltisLife because we might rush releases, release unfinished work or not be able to fit in there release schedule.

**Comment by MightySCollins** [comment]
I will merge this and keep the old version downloadable from our site. https://cyberbyte.org.uk/files/file/1-cyberworks/

**Pull request merged**
