### PR TITLE
Fix column names in SQL queries

### PR DESCRIPTION
**Pull request by vbrandl**
The column `players.donorlevel` has been renamed to `players.donatorlvl`

### CODE REVIEW

**Comment by BoGuu** [comment]
Sorry where has this been renamed?

**Comment by vbrandl** [comment]
The columns in the Altis life database. I just changed the names in the SQL queries. I had problems using CyberWorks until I fixed the SQL queries

**Comment by BoGuu** [comment]
donorlevel is the new column name for latest AL versions

**Comment by MightySCollins** [comment]
I am thinking of putting this in a branch then for legacy servers

**Comment by BoGuu** [comment]
Give me a few mins

**Comment by BoGuu** [comment]
Test the latest build

**Pull request closed without merging**
