### PR TITLE
Update German Language

### PR DESCRIPTION
**Pull request by Thiritin**

### CODE REVIEW

**Comment by Thiritin** [comment]
#32

**Comment by cammygames** [comment]
Thanks. ill merge this in after the update is out today!

**Comment by MightySCollins** [comment]
@cammygames remeber to add it to the list of strings supported to it can be activated, but I was sure we already had a German Translation in the CyberWorks Framework repo

**Comment by Thiritin** [comment]
@MightySCollins hmm i couldnt find a file to add the translation. Could you please tell me which list you mean?

**Comment by MightySCollins** [comment]
This has been added in f7aa577caec8470007c11bd623bd0fad33f10cb3

**Comment by MightySCollins** [comment]
I know its been a while but if you feel like translating our new version that would help alot https://github.com/Cyberbyte-Studios/CyberWorks-3/wiki/Translations.

**Pull request closed without merging**
